[build]
  publish = "dist/finance/browser"
  command = "npm run netlify:build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
