[build]
  command = "npm install --legacy-peer-deps && npm run netlify:build"
  publish = "dist/finance/browser"
  functions = "netlify/functions"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200
