[build]
  publish = "dist/finance/browser"
  command = "npm run build"


[build.environment]
  NODE_VERSION = "22"

  [[redirects]]
  from = "/:route/"
  to = "/:route"
  status = 301
  force = true

[[redirects]]
  from = "/:route/:subroute/"
  to = "/:route/:subroute"
  status = 301
  force = true

[[redirects]]
  from = "/:route/:subroute/:deep/"
  to = "/:route/:subroute/:deep"
  status = 301
  force = true

  [dev]
  framework = "custom"