export const AppRoutes = {
  HOME: '',
  RENDEMENT: 'rendement-locatif',
  BUDGET: 'budget-immobilier',
  INVESTISSEMENT: 'investissement-locatif',
  CASHFLOW: 'cashflow-immobilier',
  EMPRUNT: 'calcul-emprunt',
  TRI: 'tri-immobilier',
  ACHAT_VS_LOCATION: 'achat-vs-location',
  CALCUL_NOTAIRE: 'calcul-frais-de-notaire',
  INTERET_COMPOSE: 'interet-compose',
  LMNP_LMP: 'lmnp-lmp-regime-fiscal',
  CALCULATRICE: 'calculatrice',
  IMPOT_REVENUE: 'simulateur-impot-revenue',
  PRIME_ACTIVITE: 'simulateur-prime-activite',
  CONVERTISSEUR_BRUT_NET: 'simulateur-brut-net',
  IMPOT_FORTUNE_IMMOBILIERE: 'simulateur-impot-fortune-immobiliere',
  INDEPENDANCE_FINANCIERE: 'simulateur-independance-financiere',
  RETRAITE: 'simulateur-retraite',
  PLUS_VALUE_IMMOBILIERE: 'simulateur-plus-value-immobiliere',
  SCI_VS_IR: 'comparateur-sci-impot',

};
