export const AppRoutes = {
  HOME: '',
  RENDEMENT: 'rendement-locatif',
  BUDGET: 'budget-immobilier',
  INVESTISSEMENT: 'investissement-locatif',
  CASHFLOW: 'cashflow-immobilier',
  EMPRUNT: 'calcul-emprunt',
  TRI: 'tri-immobilier',
  ACHAT_VS_LOCATION: 'achat-vs-location',
  CALCUL_NOTAIRE: 'calcul-frais-de-notaire',
  INTERET_COMPOSE: 'interet-compose',
  LMNP_LMP: 'lmnp-lmp-regime-fiscal',
  CALCULATRICE: 'calculatrice',
  IMPOT_REVENUE: 'simulateur-impot-revenue',
  PRIME_ACTIVITE: 'simulateur-prime-activite',
  CONVERTISSEUR_BRUT_NET: 'simulateur-brut-net',
  IMPOT_FORTUNE_IMMOBILIERE: 'simulateur-impot-fortune-immobiliere',
  INDEPENDANCE_FINANCIERE: 'simulateur-independance-financiere',
  RETRAITE: 'simulateur-retraite',
  PLUS_VALUE_IMMOBILIERE: 'simulateur-plus-value-immobiliere',
  SCI_VS_IR: 'comparateur-sci-impot',
  CREDIT_LOMBARD: 'simulateur-credit-lombard',
  ARTICLE_PEA: 'article/pea',
  ARTICLE_ASSURANCE_VIE: 'article/assurance-vie',
  ARTICLE_PEA_VS_ASSURANCE_VIE: 'article/pea-vs-assurance-vie',
  ARTICLE_PERCO: 'article/perco',
  ARTICLE_PER: 'article/per',
  ARTICLE_CTO: 'article/cto',
  ARTICLE_ASSURANCE_VIE_LUX: 'article/assurance-vie-luxembourgeoise',
  ARTICLE_CREDIT_LOMBARD: 'article/credit-lombard',
  SIMULATEUR__LOCATION_NUE_REGIME: 'simulateur-location-nue-regime',
  SIMULATEUR_APPORT_VS_EMPRUNT: 'simulateur-apport-vs-emprunt',
  AIRBNB_VS_LOCATION: 'airbnb-vs-location',
  SIMULATEUR_DIVIDEND_FIRE: 'simulateur-dividend-fire',

};
